# Generated by Django 5.1.1 on 2024-10-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("surname", models.CharField(max_length=64)),
                ("year", models.IntegerField()),
                ("student_id", models.IntegerField()),
            ],
        ),
    ]
