# Generated by Django 5.1.1 on 2024-10-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=64)),
                ("semester", models.IntegerField()),
                ("year", models.IntegerField()),
                ("seats", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("AVAILABLE", "Available"), ("FULL", "Full")],
                        default="AVAILABLE",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
