# Generated by Django 5.1.1 on 2024-10-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="subjects", to="login.student"
            ),
        ),
    ]
