# Generated by Django 5.1.1 on 2024-10-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0005_remove_subject_students_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="enrolled",
            field=models.BooleanField(default=False),
        ),
    ]
