# Generated by Django 5.1.1 on 2024-10-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0006_alter_student_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("FULL", "Full"),
                    ("REGISTERED", "Registered"),
                ],
                default="AVAILABLE",
                max_length=10,
            ),
        ),
    ]
