# Generated by Django 5.1.1 on 2024-11-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0006_student_enrolled"),
        ("login", "0007_alter_subject_status"),
    ]

    operations = []
