# Generated by Django 5.1.1 on 2024-11-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0008_merge_0006_student_enrolled_0007_alter_subject_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="enrolled",
        ),
    ]
